name: 保持仓库运行

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *" # 每月 1 日运行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: EndBug/add-and-commit@v9.1.0
        with:
          commit: --allow-empty
          message: "An empty commit to keep github actions alive"
          new_branch: keep-github-actions-alive
