name: 自动运行

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9,22 * * *" # 每天运行 6:00, 17:00 两次 (UTC+8)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v2
      - name: 同步上游分支
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.1
        with:
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_branch: main
          upstream_sync_repo: xiaotianxt/PKU-SIMSO-FREE
      - name: 安装 python
        uses: actions/setup-python@v2
      - name: 安装依赖
        run: pip3 install requests requests_toolbelt
      - name: 运行
        env:
          STUDENTID: ${{secrets.STUDENTID}}
          PASSWORD: ${{secrets.PASSWORD}}
          DESCRIPTION: ${{secrets.DESCRIPTION}}
          PLACES: ${{secrets.PLACES}}
          DELTA: ${{secrets.DELTA}}
        run: python3 main.py
